// SPDX-FileCopyrightText: 2024 PK Lab AG <contact@pklab.io>
// SPDX-License-Identifier: MIT

// Code generated by MockGen. DO NOT EDIT.
// Source: action.go
//
// Generated by this command:
//
//	mockgen -source=action.go -destination=mock/action.go -package=mock -typed
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	storage "github.com/celenium-io/astria-indexer/internal/storage"
	types "github.com/celenium-io/astria-indexer/pkg/types"
	storage0 "github.com/dipdup-net/indexer-sdk/pkg/storage"
	gomock "go.uber.org/mock/gomock"
)

// MockIAction is a mock of IAction interface.
type MockIAction struct {
	ctrl     *gomock.Controller
	recorder *MockIActionMockRecorder
}

// MockIActionMockRecorder is the mock recorder for MockIAction.
type MockIActionMockRecorder struct {
	mock *MockIAction
}

// NewMockIAction creates a new mock instance.
func NewMockIAction(ctrl *gomock.Controller) *MockIAction {
	mock := &MockIAction{ctrl: ctrl}
	mock.recorder = &MockIActionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAction) EXPECT() *MockIActionMockRecorder {
	return m.recorder
}

// ByAddress mocks base method.
func (m *MockIAction) ByAddress(ctx context.Context, addressId uint64, filters storage.AddressActionsFilter) ([]storage.AddressAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ByAddress", ctx, addressId, filters)
	ret0, _ := ret[0].([]storage.AddressAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ByAddress indicates an expected call of ByAddress.
func (mr *MockIActionMockRecorder) ByAddress(ctx, addressId, filters any) *MockIActionByAddressCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ByAddress", reflect.TypeOf((*MockIAction)(nil).ByAddress), ctx, addressId, filters)
	return &MockIActionByAddressCall{Call: call}
}

// MockIActionByAddressCall wrap *gomock.Call
type MockIActionByAddressCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIActionByAddressCall) Return(arg0 []storage.AddressAction, arg1 error) *MockIActionByAddressCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIActionByAddressCall) Do(f func(context.Context, uint64, storage.AddressActionsFilter) ([]storage.AddressAction, error)) *MockIActionByAddressCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIActionByAddressCall) DoAndReturn(f func(context.Context, uint64, storage.AddressActionsFilter) ([]storage.AddressAction, error)) *MockIActionByAddressCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ByBlock mocks base method.
func (m *MockIAction) ByBlock(ctx context.Context, height types.Level, limit, offset int) ([]storage.ActionWithTx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ByBlock", ctx, height, limit, offset)
	ret0, _ := ret[0].([]storage.ActionWithTx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ByBlock indicates an expected call of ByBlock.
func (mr *MockIActionMockRecorder) ByBlock(ctx, height, limit, offset any) *MockIActionByBlockCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ByBlock", reflect.TypeOf((*MockIAction)(nil).ByBlock), ctx, height, limit, offset)
	return &MockIActionByBlockCall{Call: call}
}

// MockIActionByBlockCall wrap *gomock.Call
type MockIActionByBlockCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIActionByBlockCall) Return(arg0 []storage.ActionWithTx, arg1 error) *MockIActionByBlockCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIActionByBlockCall) Do(f func(context.Context, types.Level, int, int) ([]storage.ActionWithTx, error)) *MockIActionByBlockCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIActionByBlockCall) DoAndReturn(f func(context.Context, types.Level, int, int) ([]storage.ActionWithTx, error)) *MockIActionByBlockCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ByRollup mocks base method.
func (m *MockIAction) ByRollup(ctx context.Context, rollupId uint64, limit, offset int, sort storage0.SortOrder) ([]storage.RollupAction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ByRollup", ctx, rollupId, limit, offset, sort)
	ret0, _ := ret[0].([]storage.RollupAction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ByRollup indicates an expected call of ByRollup.
func (mr *MockIActionMockRecorder) ByRollup(ctx, rollupId, limit, offset, sort any) *MockIActionByRollupCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ByRollup", reflect.TypeOf((*MockIAction)(nil).ByRollup), ctx, rollupId, limit, offset, sort)
	return &MockIActionByRollupCall{Call: call}
}

// MockIActionByRollupCall wrap *gomock.Call
type MockIActionByRollupCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIActionByRollupCall) Return(arg0 []storage.RollupAction, arg1 error) *MockIActionByRollupCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIActionByRollupCall) Do(f func(context.Context, uint64, int, int, storage0.SortOrder) ([]storage.RollupAction, error)) *MockIActionByRollupCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIActionByRollupCall) DoAndReturn(f func(context.Context, uint64, int, int, storage0.SortOrder) ([]storage.RollupAction, error)) *MockIActionByRollupCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ByTxId mocks base method.
func (m *MockIAction) ByTxId(ctx context.Context, txId uint64, limit, offset int) ([]storage.Action, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ByTxId", ctx, txId, limit, offset)
	ret0, _ := ret[0].([]storage.Action)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ByTxId indicates an expected call of ByTxId.
func (mr *MockIActionMockRecorder) ByTxId(ctx, txId, limit, offset any) *MockIActionByTxIdCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ByTxId", reflect.TypeOf((*MockIAction)(nil).ByTxId), ctx, txId, limit, offset)
	return &MockIActionByTxIdCall{Call: call}
}

// MockIActionByTxIdCall wrap *gomock.Call
type MockIActionByTxIdCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIActionByTxIdCall) Return(arg0 []storage.Action, arg1 error) *MockIActionByTxIdCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIActionByTxIdCall) Do(f func(context.Context, uint64, int, int) ([]storage.Action, error)) *MockIActionByTxIdCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIActionByTxIdCall) DoAndReturn(f func(context.Context, uint64, int, int) ([]storage.Action, error)) *MockIActionByTxIdCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CursorList mocks base method.
func (m *MockIAction) CursorList(ctx context.Context, id, limit uint64, order storage0.SortOrder, cmp storage0.Comparator) ([]*storage.Action, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CursorList", ctx, id, limit, order, cmp)
	ret0, _ := ret[0].([]*storage.Action)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CursorList indicates an expected call of CursorList.
func (mr *MockIActionMockRecorder) CursorList(ctx, id, limit, order, cmp any) *MockIActionCursorListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CursorList", reflect.TypeOf((*MockIAction)(nil).CursorList), ctx, id, limit, order, cmp)
	return &MockIActionCursorListCall{Call: call}
}

// MockIActionCursorListCall wrap *gomock.Call
type MockIActionCursorListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIActionCursorListCall) Return(arg0 []*storage.Action, arg1 error) *MockIActionCursorListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIActionCursorListCall) Do(f func(context.Context, uint64, uint64, storage0.SortOrder, storage0.Comparator) ([]*storage.Action, error)) *MockIActionCursorListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIActionCursorListCall) DoAndReturn(f func(context.Context, uint64, uint64, storage0.SortOrder, storage0.Comparator) ([]*storage.Action, error)) *MockIActionCursorListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByID mocks base method.
func (m *MockIAction) GetByID(ctx context.Context, id uint64) (*storage.Action, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*storage.Action)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockIActionMockRecorder) GetByID(ctx, id any) *MockIActionGetByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockIAction)(nil).GetByID), ctx, id)
	return &MockIActionGetByIDCall{Call: call}
}

// MockIActionGetByIDCall wrap *gomock.Call
type MockIActionGetByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIActionGetByIDCall) Return(arg0 *storage.Action, arg1 error) *MockIActionGetByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIActionGetByIDCall) Do(f func(context.Context, uint64) (*storage.Action, error)) *MockIActionGetByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIActionGetByIDCall) DoAndReturn(f func(context.Context, uint64) (*storage.Action, error)) *MockIActionGetByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IsNoRows mocks base method.
func (m *MockIAction) IsNoRows(err error) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsNoRows", err)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsNoRows indicates an expected call of IsNoRows.
func (mr *MockIActionMockRecorder) IsNoRows(err any) *MockIActionIsNoRowsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsNoRows", reflect.TypeOf((*MockIAction)(nil).IsNoRows), err)
	return &MockIActionIsNoRowsCall{Call: call}
}

// MockIActionIsNoRowsCall wrap *gomock.Call
type MockIActionIsNoRowsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIActionIsNoRowsCall) Return(arg0 bool) *MockIActionIsNoRowsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIActionIsNoRowsCall) Do(f func(error) bool) *MockIActionIsNoRowsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIActionIsNoRowsCall) DoAndReturn(f func(error) bool) *MockIActionIsNoRowsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// LastID mocks base method.
func (m *MockIAction) LastID(ctx context.Context) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastID", ctx)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LastID indicates an expected call of LastID.
func (mr *MockIActionMockRecorder) LastID(ctx any) *MockIActionLastIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastID", reflect.TypeOf((*MockIAction)(nil).LastID), ctx)
	return &MockIActionLastIDCall{Call: call}
}

// MockIActionLastIDCall wrap *gomock.Call
type MockIActionLastIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIActionLastIDCall) Return(arg0 uint64, arg1 error) *MockIActionLastIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIActionLastIDCall) Do(f func(context.Context) (uint64, error)) *MockIActionLastIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIActionLastIDCall) DoAndReturn(f func(context.Context) (uint64, error)) *MockIActionLastIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockIAction) List(ctx context.Context, limit, offset uint64, order storage0.SortOrder) ([]*storage.Action, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, limit, offset, order)
	ret0, _ := ret[0].([]*storage.Action)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockIActionMockRecorder) List(ctx, limit, offset, order any) *MockIActionListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIAction)(nil).List), ctx, limit, offset, order)
	return &MockIActionListCall{Call: call}
}

// MockIActionListCall wrap *gomock.Call
type MockIActionListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIActionListCall) Return(arg0 []*storage.Action, arg1 error) *MockIActionListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIActionListCall) Do(f func(context.Context, uint64, uint64, storage0.SortOrder) ([]*storage.Action, error)) *MockIActionListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIActionListCall) DoAndReturn(f func(context.Context, uint64, uint64, storage0.SortOrder) ([]*storage.Action, error)) *MockIActionListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Save mocks base method.
func (m_2 *MockIAction) Save(ctx context.Context, m *storage.Action) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Save", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockIActionMockRecorder) Save(ctx, m any) *MockIActionSaveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockIAction)(nil).Save), ctx, m)
	return &MockIActionSaveCall{Call: call}
}

// MockIActionSaveCall wrap *gomock.Call
type MockIActionSaveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIActionSaveCall) Return(arg0 error) *MockIActionSaveCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIActionSaveCall) Do(f func(context.Context, *storage.Action) error) *MockIActionSaveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIActionSaveCall) DoAndReturn(f func(context.Context, *storage.Action) error) *MockIActionSaveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m_2 *MockIAction) Update(ctx context.Context, m *storage.Action) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Update", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIActionMockRecorder) Update(ctx, m any) *MockIActionUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIAction)(nil).Update), ctx, m)
	return &MockIActionUpdateCall{Call: call}
}

// MockIActionUpdateCall wrap *gomock.Call
type MockIActionUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIActionUpdateCall) Return(arg0 error) *MockIActionUpdateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIActionUpdateCall) Do(f func(context.Context, *storage.Action) error) *MockIActionUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIActionUpdateCall) DoAndReturn(f func(context.Context, *storage.Action) error) *MockIActionUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
